### ISSUE TITLE
Show real arrival time if bus is early

### ISSUE THREAD

**Issue by fcucino** [Stypox/tridenta#8]
At the moment, v1.2 of the application shows the real arrival time only if the bus is late and not if early.
I think it could be really useful to show the real arrival time in both cases.

<table>
  <tr>
    <th>Early (not showed)</th>
    <th>Late (showed)</th>
  </tr>
  <tr>
    <td><img src="https://github.com/Stypox/tridenta/assets/24813315/b7ee0c35-b8b6-46c0-b1c4-880a49d8ab80" width="200px" alt="Before"/></td>
    <td><img src="https://github.com/Stypox/tridenta/assets/24813315/f3271b79-6b2d-4f29-9a5d-6efb57ccb3f1" width="200px" alt="After"/></td>
  </tr>
</table>

**Comment by Stypox** [comment]
Usually when a bus is early it will still need to wait at the next stop until it is on time, that's why it works like that

**Comment by fcucino** [comment]
I'm with you on that, but I wrote this because the official app "Muoversi in Trentino" started showing the real arrival time if it is early (I talk for the urban buses). 

Could be showed with the notation

stop name --> **highlighted real arrival time** >> expected departure time

**Comment by Stypox** [comment]
I am sorry, but I disagree with showing the real arrival time if the bus is early. I think it would just confuse most people, without actually being a relevant information, because the bus will usually wait at the next stop until it's not early anymore.
